### PR TITLE
Moved simClock increment; implemented random.choices().  Refactored vaccine protection

### PR DESCRIPTION
**Pull request by tedkyi**
Quick commit that makes two small changes Roger and I discussed:
* Moved the increment of simClock to the beginning of `tick()`
* Changed the initialization of variants to use `random.choices()`

### CODE REVIEW

**Comment by tedkyi** [comment]
Second commit has the new vaccination code:
* Vaccine protection is now a float for each actor; got rid of booleans
* There is a spot to calculate the waning protection based on how many days since vaccination
TODO:  Someone needs to put in a reasonable curve for waning protection

**Comment by tedkyi** [comment]
Third commit has reinfections that work similar to vaccinations, as a multiplicative float:
* Recovered resistance is based on prior variant(s) and new variant
* If multiple prior, currently takes the max
* There is a spot to calculate the waning protection based on how many days since infection
TODO: Someone needs to put in a reasonable curve for waning protection

**Comment by rstager** [comment]
Ted,  I think simulation.py:181 (recovered resistance)  is redundant with line 128.  I will merge and we can clean up on main branch.

**Comment by tedkyi** [comment]
@rstager, thanks for reviewing.  The way the `VariantParameters` class works is that it defines default values.  Initially all variants have the same values.  The stuff near line 128 is where `SimulationParameters.__init__()` overrides these defaults and sets different values for certain parameters for certain variants.  So yes, it does set the same parameters, but it's on purpose as an example how to have different values for different variants.

**Pull request merged**
